FROM golang:1.9-alpine as golang-builder

WORKDIR /go/src/github.com/martinohmann/rfoutlet

ADD glide.lock .
ADD glide.yaml .

RUN apk --no-cache add git && \
	go get -u github.com/Masterminds/glide && \
	glide install

ADD cmd/ cmd/
ADD internal/ internal/
ADD pkg/ pkg/

ARG GOARCH=arm
ARG GOARM=7

RUN CGO_ENABLED=0 GOOS=linux go build ./cmd/rfsniff

FROM scratch

COPY --from=golang-builder /go/src/github.com/martinohmann/rfoutlet/rfsniff /rfsniff

ENTRYPOINT ["/rfsniff"]
