FROM golang:1.13.4-alpine3.10 as golang-builder

WORKDIR /go/src/github.com/martinohmann/rfoutlet

RUN apk --no-cache add git

ARG GOARCH=arm
ARG GOARM=7

ADD go.mod .
ADD go.sum .

RUN go mod download

ADD cmd/ cmd/
ADD internal/ internal/
ADD pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux go build ./cmd/rfsniff

FROM scratch

COPY --from=golang-builder /go/src/github.com/martinohmann/rfoutlet/rfsniff /rfsniff

ENTRYPOINT ["/rfsniff"]
