FROM golang:1.9-alpine as golang-builder

WORKDIR /go/src/github.com/martinohmann/rfoutlet

ADD cmd/ cmd/
ADD internal/ internal/
ADD pkg/ pkg/
ADD glide.lock .
ADD glide.yaml .

RUN apk --no-cache add git && \
	go get -u github.com/Masterminds/glide && \
	glide install

ARG GOARCH=arm
ARG GOARM=7

RUN CGO_ENABLED=0 GOOS=linux go build ./cmd/rftransmit

FROM scratch

COPY --from=golang-builder /go/src/github.com/martinohmann/rfoutlet/rftransmit /rftransmit

ENTRYPOINT ["/rftransmit"]
